#!/bin/bash
# -------------------------------------------------------
# Virtuoso on AWS - Interactive Deployment Script
# -------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TFVARS_FILE="${SCRIPT_DIR}/terraform.tfvars"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

fail() {
    echo -e "${RED}Error: $1${NC}" >&2
    exit 1
}

require_single_line() {
    local value="$1"
    local label="$2"
    case "$value" in
        *$'\n'*|*$'\r'*) fail "$label must be a single-line value" ;;
    esac
}

escape_tf_string() {
    local value="$1"
    local label="${2:-value}"
    require_single_line "$value" "$label"
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    printf '%s' "$value"
}


validate_cidr_list() {
    local list_value="$1"
    local label="$2"
    local IFS=','
    local item
    local -a parts
    read -r -a parts <<< "$list_value"
    [ ${#parts[@]} -gt 0 ] || fail "$label must contain at least one CIDR"
    for item in "${parts[@]}"; do
        item="${item//[[:space:]]/}"
        [[ -n "$item" ]] || fail "$label contains an empty CIDR entry"
        [[ "$item" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}/[0-9]{1,2}$ ]] || fail "$label contains an invalid CIDR: $item"
    done
}

print_header() {
    echo ""
    echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}  Virtuoso on AWS – Interactive Deployment${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo ""
}

print_section() {
    echo ""
    echo -e "${GREEN}─── $1 ───${NC}"
    echo ""
}

# Check for required tools
check_prerequisites() {
    local missing=()

    if ! command -v tofu &> /dev/null && ! command -v terraform &> /dev/null; then
        missing+=("tofu or terraform")
    fi

    if ! command -v aws &> /dev/null; then
        missing+=("aws-cli")
    fi

    if [ ${#missing[@]} -ne 0 ]; then
        echo -e "${RED}Error: Missing required tools: ${missing[*]}${NC}"
        exit 1
    fi

    # Prefer tofu over terraform
    if command -v tofu &> /dev/null; then
        TF_CMD="tofu"
    else
        TF_CMD="terraform"
    fi
}

# Read current value from terraform.tfvars if it exists
get_current_value() {
    local var_name="$1"
    local default="$2"

    if [ -f "$TFVARS_FILE" ]; then
        # Use awk for more reliable parsing
        local value=$(awk -F'=' -v var="$var_name" '
            $0 ~ "^"var"[[:space:]]*=" {
                # Get everything after the =
                sub(/^[^=]*=[[:space:]]*/, "")
                # Remove surrounding quotes if present
                gsub(/^[[:space:]]*"?|"?[[:space:]]*$/, "")
                print
                exit
            }
        ' "$TFVARS_FILE" 2>/dev/null)
        if [ -n "$value" ]; then
            echo "$value"
            return
        fi
    fi
    echo "$default"
}

# Update or add a variable in terraform.tfvars
set_tfvar() {
    local var_name="$1"
    local var_value="$2"
    local is_string="${3:-true}"

    # Create file if it doesn't exist
    if [ ! -f "$TFVARS_FILE" ]; then
        cat > "$TFVARS_FILE" << 'EOF'
# -------------------------------------------------------
# Virtuoso on AWS – Configuration
# Generated by deploy.sh
# -------------------------------------------------------

EOF
    fi

    # Format the value
    if [ "$is_string" = "true" ]; then
        local formatted_value="\"$(escape_tf_string "$var_value" "$var_name")\""
    else
        local formatted_value="${var_value}"
    fi

    # Check if variable exists in file
    if grep -q "^${var_name}[[:space:]]*=" "$TFVARS_FILE" 2>/dev/null; then
        # Update existing variable (macOS compatible sed)
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s|^${var_name}[[:space:]]*=.*|${var_name} = ${formatted_value}|" "$TFVARS_FILE"
        else
            sed -i "s|^${var_name}[[:space:]]*=.*|${var_name} = ${formatted_value}|" "$TFVARS_FILE"
        fi
    else
        # Add new variable
        echo "${var_name} = ${formatted_value}" >> "$TFVARS_FILE"
    fi
}

# Prompt for Virtuoso image selection
select_virtuoso_image() {
    print_section "Virtuoso Image Selection"

    echo "Select the Virtuoso image to deploy:"
    echo ""

    local options=(
        "Virtuoso Open Source 7 (Free, community edition)"
        "Virtuoso Commercial 8 (Requires license file)"
    )

    PS3=$'\nEnter selection [1-2]: '
    select opt in "${options[@]}"; do
        case $REPLY in
            1)
                VIRTUOSO_IMAGE="openlink/virtuoso-opensource-7"
                VIRTUOSO_LICENSE_REQUIRED=false
                echo -e "${GREEN}Selected: Virtuoso Open Source 7${NC}"
                break
                ;;
            2)
                VIRTUOSO_IMAGE="openlink/virtuoso-closedsource-8"
                VIRTUOSO_LICENSE_REQUIRED=true
                echo -e "${GREEN}Selected: Virtuoso Commercial 8${NC}"
                break
                ;;
            *)
                echo -e "${RED}Invalid selection. Please enter 1 or 2.${NC}"
                ;;
        esac
    done

    # Prompt for image tag
    local current_tag=$(get_current_value "virtuoso_image_tag" "latest")
    echo ""
    read -p "Enter image tag [${current_tag}]: " IMAGE_TAG
    IMAGE_TAG="${IMAGE_TAG:-$current_tag}"

    set_tfvar "virtuoso_image" "$VIRTUOSO_IMAGE"
    set_tfvar "virtuoso_image_tag" "$IMAGE_TAG"
    set_tfvar "web_allowed_cidrs" '["0.0.0.0/0"]' false
    set_tfvar "virtuoso_number_of_buffers" "60%"
    set_tfvar "virtuoso_max_dirty_buffers" "45%"
}

# Prompt for license file if using commercial image
select_license_file() {
    if [ "$VIRTUOSO_LICENSE_REQUIRED" = true ]; then
        print_section "License File"

        echo -e "${YELLOW}Virtuoso Commercial 8 requires a license file.${NC}"
        echo "The license file will be copied to the EFS storage after deployment."
        echo ""

        while true; do
            read -p "Enter path to license file (virtuoso.lic): " LICENSE_PATH

            if [ -z "$LICENSE_PATH" ]; then
                echo -e "${RED}License file is required for Commercial edition.${NC}"
                continue
            fi

            # Expand ~ to home directory
            LICENSE_PATH="${LICENSE_PATH/#\~/$HOME}"

            if [ ! -f "$LICENSE_PATH" ]; then
                echo -e "${RED}File not found: ${LICENSE_PATH}${NC}"
                continue
            fi

            VIRTUOSO_LICENSE_FILE="$LICENSE_PATH"
            echo -e "${GREEN}License file: ${LICENSE_PATH}${NC}"
            set_tfvar "virtuoso_license_file" "$LICENSE_PATH"
            break
        done
    else
        set_tfvar "virtuoso_license_file" ""
    fi
}

# Prompt for container size
select_container_size() {
    print_section "Container Size"

    echo "Select the container size for your workload:"
    echo ""

    local options=(
        "Development      (0.5 vCPU,  1 GB RAM) - Testing and development"
        "Small Production (1 vCPU,    2 GB RAM) - Light workloads"
        "Medium Production(2 vCPU,    4 GB RAM) - Standard workloads"
        "Large Production (4 vCPU,    8 GB RAM) - Heavy workloads"
        "Extra Large      (8 vCPU,   16 GB RAM) - Very heavy workloads"
        "Custom           (Specify CPU and memory manually)"
    )

    PS3=$'\nEnter selection [1-6]: '
    select opt in "${options[@]}"; do
        case $REPLY in
            1)
                ECS_CPU="512"
                ECS_MEMORY="1024"
                echo -e "${GREEN}Selected: Development (0.5 vCPU, 1 GB)${NC}"
                break
                ;;
            2)
                ECS_CPU="1024"
                ECS_MEMORY="2048"
                echo -e "${GREEN}Selected: Small Production (1 vCPU, 2 GB)${NC}"
                break
                ;;
            3)
                ECS_CPU="2048"
                ECS_MEMORY="4096"
                echo -e "${GREEN}Selected: Medium Production (2 vCPU, 4 GB)${NC}"
                break
                ;;
            4)
                ECS_CPU="4096"
                ECS_MEMORY="8192"
                echo -e "${GREEN}Selected: Large Production (4 vCPU, 8 GB)${NC}"
                break
                ;;
            5)
                ECS_CPU="8192"
                ECS_MEMORY="16384"
                echo -e "${GREEN}Selected: Extra Large (8 vCPU, 16 GB)${NC}"
                break
                ;;
            6)
                select_custom_size
                break
                ;;
            *)
                echo -e "${RED}Invalid selection. Please enter 1-6.${NC}"
                ;;
        esac
    done

    set_tfvar "ecs_cpu" "$ECS_CPU"
    set_tfvar "ecs_memory" "$ECS_MEMORY"
}

configure_sql_exposure() {
    print_section "SQL Endpoint Exposure"

    read -r -p "Expose public secure SQL/ODBC/JDBC endpoint on port 1112? [y/N]: " EXPOSE_SQL
    EXPOSE_SQL=${EXPOSE_SQL:-N}
    if [[ "$EXPOSE_SQL" =~ ^[Yy]$ ]]; then
        cat <<'EOF'
Enter one or more CIDR blocks allowed to reach secure SQL on port 1112.
Examples:
  203.0.113.45/32
  203.0.113.45/32,198.51.100.27/32
  203.0.113.0/24

Use your current public IP with /32 for single-user access.
WARNING: 0.0.0.0/0 exposes secure SQL to the entire public internet.
EOF
        read -r -p "Allowed SQL CIDRs (comma-separated, required): " SQL_ALLOWED_CIDRS
        [ -n "$SQL_ALLOWED_CIDRS" ] || fail "Allowed SQL CIDRs are required when SQL exposure is enabled"
        validate_cidr_list "$SQL_ALLOWED_CIDRS" "Allowed SQL CIDRs"
        SQL_ALLOWED_CIDRS="$(printf '%s' "$SQL_ALLOWED_CIDRS" | sed 's/[[:space:]]//g')"
        set_tfvar "expose_sql_endpoint" true false
        set_tfvar "sql_allowed_cidrs" "[\"${SQL_ALLOWED_CIDRS//,/\",\"}\"]" false
    else
        set_tfvar "expose_sql_endpoint" false false
        set_tfvar "sql_allowed_cidrs" "[]" false
    fi
}

# Custom size selection
select_custom_size() {
    echo ""
    echo "Valid CPU values: 256, 512, 1024, 2048, 4096, 8192, 16384"
    echo ""
    echo "Valid CPU/Memory combinations:"
    echo "  CPU=256:   Memory=512, 1024, 2048"
    echo "  CPU=512:   Memory=1024, 2048, 3072, 4096"
    echo "  CPU=1024:  Memory=2048-8192 (1GB steps)"
    echo "  CPU=2048:  Memory=4096-16384 (1GB steps)"
    echo "  CPU=4096:  Memory=8192-30720 (1GB steps)"
    echo "  CPU=8192:  Memory=16384-61440 (4GB steps)"
    echo "  CPU=16384: Memory=32768-122880 (8GB steps)"
    echo ""

    while true; do
        read -p "Enter CPU units: " ECS_CPU
        if [[ "$ECS_CPU" =~ ^(256|512|1024|2048|4096|8192|16384)$ ]]; then
            break
        fi
        echo -e "${RED}Invalid CPU value. Must be one of: 256, 512, 1024, 2048, 4096, 8192, 16384${NC}"
    done

    read -p "Enter Memory (MiB): " ECS_MEMORY
    echo -e "${GREEN}Selected: Custom (${ECS_CPU} CPU units, ${ECS_MEMORY} MiB memory)${NC}"
}

# Prompt for AWS region
select_region() {
    print_section "AWS Region"

    local current_region=$(get_current_value "region" "us-east-1")

    read -p "Enter AWS region [${current_region}]: " REGION
    REGION="${REGION:-$current_region}"

    set_tfvar "region" "$REGION"
    echo -e "${GREEN}Region: ${REGION}${NC}"
}

# Prompt for project name
select_project_name() {
    print_section "Project Name"

    local current_name=$(get_current_value "project_name" "virtuoso")

    echo "Project name is used as a prefix for all AWS resources."
    read -p "Enter project name [${current_name}]: " PROJECT_NAME
    PROJECT_NAME="${PROJECT_NAME:-$current_name}"

    set_tfvar "project_name" "$PROJECT_NAME"
    echo -e "${GREEN}Project name: ${PROJECT_NAME}${NC}"
}

# Prompt for provider-native scheduled backup sync
configure_backup_schedule() {
    print_section "Backup Scheduling"

    echo "Virtuoso online backup has two parts:"
    echo "  1. A Virtuoso internal scheduled event creates consistent .bp backup files."
    echo "  2. AWS EventBridge runs an ECS backup-sync task to copy those files to S3."
    echo ""
    echo -e "${YELLOW}Recommended for production deployments.${NC}"
    echo ""

    local current_enabled=$(get_current_value "enable_backup_sync_schedule" "false")
    local default_answer="N"
    if [ "$current_enabled" = "true" ]; then
        default_answer="Y"
    fi

    if [ "$default_answer" = "Y" ]; then
        read -p "Enable provider-native scheduled backup sync? [Y/n]: " ENABLE_BACKUP_SCHEDULE
    else
        read -p "Enable provider-native scheduled backup sync? [y/N]: " ENABLE_BACKUP_SCHEDULE
    fi
    ENABLE_BACKUP_SCHEDULE="${ENABLE_BACKUP_SCHEDULE:-$default_answer}"

    if [[ "$ENABLE_BACKUP_SCHEDULE" =~ ^[Yy]$ ]]; then
        BACKUP_SYNC_SCHEDULE_ENABLED=true
        local current_expr=$(get_current_value "backup_sync_schedule_expression" "rate(1 day)")
        read -p "EventBridge schedule expression [${current_expr}]: " BACKUP_SYNC_SCHEDULE_EXPRESSION
        BACKUP_SYNC_SCHEDULE_EXPRESSION="${BACKUP_SYNC_SCHEDULE_EXPRESSION:-$current_expr}"
    else
        BACKUP_SYNC_SCHEDULE_ENABLED=false
        BACKUP_SYNC_SCHEDULE_EXPRESSION=$(get_current_value "backup_sync_schedule_expression" "rate(1 day)")
    fi

    set_tfvar "enable_backup_sync_schedule" "$BACKUP_SYNC_SCHEDULE_ENABLED" false
    set_tfvar "backup_sync_schedule_expression" "$BACKUP_SYNC_SCHEDULE_EXPRESSION"
}

# Install the Virtuoso internal scheduled backup event after deployment.
setup_internal_backup_schedule() {
    if [ "$(get_current_value "enable_backup_sync_schedule" "false")" = "true" ]; then
        print_section "Configuring Virtuoso Scheduled Backup"
        echo "Installing Virtuoso daily online backup event. This creates .bp files for the AWS sync schedule."
        if [ -x "${SCRIPT_DIR}/scripts/setup-scheduled-backup.sh" ]; then
            local cluster_name
            local service_name
            local region_name
            cluster_name="$($TF_CMD output -raw ecs_cluster_name)"
            service_name="$($TF_CMD output -raw ecs_service_name)"
            region_name="$($TF_CMD output -raw region 2>/dev/null || true)"
            if [ -z "$region_name" ]; then
                region_name="${AWS_REGION:-${AWS_DEFAULT_REGION:-us-east-1}}"
            fi
            echo "Waiting for ECS service to become stable before installing the Virtuoso backup schedule..."
            aws ecs wait services-stable                 --region "$region_name"                 --cluster "$cluster_name"                 --services "$service_name"
            "${SCRIPT_DIR}/scripts/setup-scheduled-backup.sh" 1440
        else
            echo -e "${YELLOW}Backup scheduler script not found or not executable.${NC}"
            echo "Run this after deployment: ./scripts/setup-scheduled-backup.sh 1440"
        fi
    fi
}

# Show configuration summary
show_summary() {
    print_section "Configuration Summary"

    echo "  Region:         ${REGION:-$(get_current_value "region" "us-east-1")}"
    echo "  Project:        ${PROJECT_NAME:-$(get_current_value "project_name" "virtuoso")}"
    echo "  Image:          ${VIRTUOSO_IMAGE}:${IMAGE_TAG}"
    if [ "$VIRTUOSO_LICENSE_REQUIRED" = true ]; then
        echo "  License:        ${VIRTUOSO_LICENSE_FILE}"
    fi
    echo "  Container Size: ${ECS_CPU} CPU units, ${ECS_MEMORY} MiB memory"
    echo "  Virtuoso Cache: NumberOfBuffers=$(get_current_value "virtuoso_number_of_buffers" "60%"), MaxDirtyBuffers=$(get_current_value "virtuoso_max_dirty_buffers" "45%")"
    echo "  Backup Sync:    $(get_current_value "enable_backup_sync_schedule" "false") ($(get_current_value "backup_sync_schedule_expression" "rate(1 day)"))"
    echo ""
}

# Determine the database path based on image type
get_database_path() {
    local image="${1:-$VIRTUOSO_IMAGE}"
    if [[ "$image" == *"closedsource"* ]]; then
        echo "/opt/virtuoso/database"
    else
        echo "/opt/virtuoso-opensource/database"
    fi
}

# Copy license file to EFS after deployment
copy_license_to_efs() {
    if [ "$VIRTUOSO_LICENSE_REQUIRED" = true ] && [ -n "$VIRTUOSO_LICENSE_FILE" ]; then
        print_section "Copying License File to EFS"

        local cluster_name="${PROJECT_NAME:-virtuoso}-cluster"
        local service_name="${PROJECT_NAME:-virtuoso}"
        local db_path=$(get_database_path)

        echo "Database path: ${db_path}"
        echo "Waiting for ECS task to be running..."

        # Wait for task to be running
        local max_attempts=30
        local attempt=0
        local task_arn=""

        while [ $attempt -lt $max_attempts ]; do
            task_arn=$(aws ecs list-tasks \
                --cluster "$cluster_name" \
                --service-name "$service_name" \
                --query 'taskArns[0]' \
                --output text 2>/dev/null)

            if [ -n "$task_arn" ] && [ "$task_arn" != "None" ]; then
                local status=$(aws ecs describe-tasks \
                    --cluster "$cluster_name" \
                    --tasks "$task_arn" \
                    --query 'tasks[0].lastStatus' \
                    --output text 2>/dev/null)

                if [ "$status" = "RUNNING" ]; then
                    echo -e "${GREEN}Task is running.${NC}"
                    break
                fi
            fi

            attempt=$((attempt + 1))
            echo "  Waiting... (attempt $attempt/$max_attempts)"
            sleep 10
        done

        if [ $attempt -eq $max_attempts ]; then
            echo -e "${RED}Timeout waiting for task to start.${NC}"
            echo "You can manually copy the license file later using:"
            echo "  ./deploy.sh --copy-license"
            return 1
        fi

        # Get task ID from ARN
        local task_id=$(echo "$task_arn" | awk -F/ '{print $NF}')

        echo "Copying license file to ${db_path}/virtuoso.lic ..."

        # Read license file content
        local license_content=$(base64 < "$VIRTUOSO_LICENSE_FILE")

        # Copy via ECS Exec using a here-document approach for reliability
        # First, write to a temp file, then move it
        aws ecs execute-command \
            --cluster "$cluster_name" \
            --task "$task_id" \
            --container virtuoso \
            --command "sh -c 'echo \"$license_content\" | base64 -d > ${db_path}/virtuoso.lic && chmod 644 ${db_path}/virtuoso.lic && ls -la ${db_path}/virtuoso.lic'" \
            --interactive

        if [ $? -eq 0 ]; then
            echo -e "${GREEN}License file copied successfully.${NC}"
            echo ""
            echo -e "${YELLOW}Restarting Virtuoso to apply the license...${NC}"
            echo "This requires a clean stop/start cycle (rolling updates won't work due to lock file)."
            echo ""

            # Stop the service (scale to 0)
            echo "Stopping service..."
            aws ecs update-service \
                --cluster "$cluster_name" \
                --service "$service_name" \
                --desired-count 0 \
                --query 'service.serviceName' \
                --output text > /dev/null

            # Wait for tasks to drain
            echo "Waiting for tasks to stop..."
            local drain_attempts=0
            local max_drain_attempts=30
            while [ $drain_attempts -lt $max_drain_attempts ]; do
                local running_count=$(aws ecs describe-services \
                    --cluster "$cluster_name" \
                    --services "$service_name" \
                    --query 'services[0].runningCount' \
                    --output text 2>/dev/null)

                if [ "$running_count" = "0" ]; then
                    echo -e "${GREEN}Service stopped.${NC}"
                    break
                fi

                drain_attempts=$((drain_attempts + 1))
                echo "  Still running: $running_count tasks (attempt $drain_attempts/$max_drain_attempts)"
                sleep 10
            done

            # Start the service (single instance)
            echo "Starting service..."
            aws ecs update-service \
                --cluster "$cluster_name" \
                --service "$service_name" \
                --desired-count 1 \
                --query 'service.serviceName' \
                --output text > /dev/null

            echo -e "${GREEN}Service restart initiated. Virtuoso will now start with the license.${NC}"
        else
            echo -e "${RED}Failed to copy license file.${NC}"
            echo ""
            echo "You can manually copy the license file by running:"
            echo "  TASK_ID=\$(aws ecs list-tasks --cluster $cluster_name --service-name $service_name --query 'taskArns[0]' --output text | awk -F/ '{print \$NF}')"
            echo "  aws ecs execute-command --cluster $cluster_name --task \$TASK_ID --container virtuoso --interactive --command '/bin/bash'"
            echo "  # Then inside the container:"
            echo "  # Copy your license content to ${db_path}/virtuoso.lic"
            return 1
        fi
    fi
}

# Run deployment
run_deployment() {
    print_section "Deployment"

    echo "Initializing ${TF_CMD}..."
    $TF_CMD init

    echo ""
    echo "Planning deployment..."
    $TF_CMD plan -out=tfplan

    echo ""
    read -p "Apply this plan? (yes/no): " CONFIRM

    if [ "$CONFIRM" = "yes" ]; then
        echo ""
        echo "Applying..."
        $TF_CMD apply tfplan
        rm -f tfplan

        # Copy license if needed
        if [ "$VIRTUOSO_LICENSE_REQUIRED" = true ]; then
            copy_license_to_efs
        fi

        setup_internal_backup_schedule

        print_section "Deployment Complete"

        echo "Outputs:"
        $TF_CMD output

        echo ""
        echo -e "${GREEN}Virtuoso has been deployed successfully!${NC}"
        echo ""
        echo "To retrieve the DBA password:"
        echo "  aws secretsmanager get-secret-value \\"
        echo "    --secret-id ${PROJECT_NAME:-virtuoso}-dba-password \\"
        echo "    --query SecretString --output text"

        if [ "$VIRTUOSO_LICENSE_REQUIRED" = true ]; then
            echo ""
            echo -e "${YELLOW}Note: Commercial license was copied and service restarted.${NC}"
            echo "Check the Virtuoso log to confirm the license was applied:"
            echo "  aws logs tail /ecs/${PROJECT_NAME:-virtuoso} --follow"
        fi
    else
        echo "Deployment cancelled."
        rm -f tfplan
    fi
}

# Main menu
main_menu() {
    print_header
    check_prerequisites

    echo "This script will guide you through configuring and deploying"
    echo "Virtuoso on AWS ECS Fargate."
    echo ""

    local options=(
        "Interactive Setup (configure and deploy)"
        "Deploy with current settings"
        "Copy license file to running deployment"
        "Destroy deployment"
        "Exit"
    )

    PS3=$'\nSelect an option: '
    select opt in "${options[@]}"; do
        case $REPLY in
            1)
                select_region
                select_project_name
                select_virtuoso_image
                select_license_file
                select_container_size
                configure_sql_exposure
                configure_backup_schedule
                show_summary

                read -p "Proceed with deployment? (yes/no): " CONFIRM
                if [ "$CONFIRM" = "yes" ]; then
                    run_deployment
                fi
                break
                ;;
            2)
                # Load current values
                VIRTUOSO_IMAGE=$(get_current_value "virtuoso_image" "openlink/virtuoso-opensource-7")
                IMAGE_TAG=$(get_current_value "virtuoso_image_tag" "latest")
                ECS_CPU=$(get_current_value "ecs_cpu" "512")
                ECS_MEMORY=$(get_current_value "ecs_memory" "1024")
                VIRTUOSO_LICENSE_FILE=$(get_current_value "virtuoso_license_file" "")
                BACKUP_SYNC_SCHEDULE_ENABLED=$(get_current_value "enable_backup_sync_schedule" "false")
                BACKUP_SYNC_SCHEDULE_EXPRESSION=$(get_current_value "backup_sync_schedule_expression" "rate(1 day)")

                if [[ "$VIRTUOSO_IMAGE" == *"closedsource"* ]]; then
                    VIRTUOSO_LICENSE_REQUIRED=true
                else
                    VIRTUOSO_LICENSE_REQUIRED=false
                fi

                show_summary
                run_deployment
                break
                ;;
            3)
                VIRTUOSO_LICENSE_REQUIRED=true
                PROJECT_NAME=$(get_current_value "project_name" "virtuoso")
                VIRTUOSO_IMAGE=$(get_current_value "virtuoso_image" "openlink/virtuoso-opensource-7")

                read -p "Enter path to license file: " VIRTUOSO_LICENSE_FILE
                VIRTUOSO_LICENSE_FILE="${VIRTUOSO_LICENSE_FILE/#\~/$HOME}"

                if [ -f "$VIRTUOSO_LICENSE_FILE" ]; then
                    copy_license_to_efs
                else
                    echo -e "${RED}File not found: ${VIRTUOSO_LICENSE_FILE}${NC}"
                fi
                break
                ;;
            4)
                print_section "Destroy Deployment"
                echo -e "${RED}WARNING: This will destroy all Virtuoso infrastructure!${NC}"
                read -p "Are you sure? (yes/no): " CONFIRM
                if [ "$CONFIRM" = "yes" ]; then
                    $TF_CMD destroy
                fi
                break
                ;;
            5)
                echo "Exiting."
                exit 0
                ;;
            *)
                echo -e "${RED}Invalid selection.${NC}"
                ;;
        esac
    done
}

# Handle command line arguments
case "${1:-}" in
    --copy-license)
        check_prerequisites
        VIRTUOSO_LICENSE_REQUIRED=true
        PROJECT_NAME=$(get_current_value "project_name" "virtuoso")
        VIRTUOSO_IMAGE=$(get_current_value "virtuoso_image" "openlink/virtuoso-opensource-7")
        VIRTUOSO_LICENSE_FILE="$2"

        if [ -z "$VIRTUOSO_LICENSE_FILE" ]; then
            read -p "Enter path to license file: " VIRTUOSO_LICENSE_FILE
        fi

        VIRTUOSO_LICENSE_FILE="${VIRTUOSO_LICENSE_FILE/#\~/$HOME}"

        if [ -f "$VIRTUOSO_LICENSE_FILE" ]; then
            copy_license_to_efs
        else
            echo -e "${RED}File not found: ${VIRTUOSO_LICENSE_FILE}${NC}"
            exit 1
        fi
        ;;
    --destroy)
        check_prerequisites
        $TF_CMD destroy
        ;;
    --help|-h)
        echo "Usage: $0 [option]"
        echo ""
        echo "Options:"
        echo "  (no args)       Interactive menu"
        echo "  --copy-license  Copy license file to running deployment"
        echo "  --destroy       Destroy the deployment"
        echo "  --help          Show this help"
        ;;
    *)
        main_menu
        ;;
esac
